PMS/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from home import views as home
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views


urlpatterns = [


    url(r'^$', home.dashboard),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^', include('product.urls', namespace="product")),
    url(r'^', include('employee.urls', namespace="employee")),
    # url(r'^login/$', auth_views.login, name='login'),
    # url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^', include('customer.urls', namespace="customer")),
    url(r'^', include('quotation.urls', namespace="quotation")),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quotation/urls.py
from django.conf.urls import include, url

from quotation import views

app_name = "quotation"


urlpatterns = [

    url(r'^quotation/', include([
        url(r'^$', views.index, name="list"),
        url(r'^create/$', views.create, name="create"),
        url(r'^(?P<pk>[^/]+)/detail/$', views.detail, name="detail"),


    ])),

]

quotation/models.py
from django.db import models
from pms_core.models import ErpAbstractBaseModel
from employee.models import Employee
from django.db import transaction
from customer.models import Customer

from django.core.validators import MinValueValidator
from decimal import Decimal
from product.models import Product
import uuid
from decimal import Decimal


class Quotation(models.Model):

    STATUS_ACCEPTED = 'accepted'
    STATUS_OPEN = 'open'
    STATUS_REJECTED = 'rejected'

    STATUSES = (
        (STATUS_OPEN, "OPEN"),
        (STATUS_ACCEPTED, "ACCEPTED"),
        (STATUS_REJECTED, "REJECTED"),

    )
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now=True)

    code = models.CharField(max_length=20, unique=True)
    status = models.CharField(max_length=30, choices=STATUSES, default=STATUS_OPEN)
    reason_for_lost = models.TextField(null=True, blank=True)
    amount = models.DecimalField(max_digits=20, decimal_places=4, default=0, null=True,
                                 blank=True, validators=[MinValueValidator(0)])
    customer = models.ForeignKey(Customer, related_name='quotation')
    created_by = models.ForeignKey(Employee, null=True, related_name='quotation_created_by')
    approved_by = models.ForeignKey(Employee, null=True, blank=True, related_name='quotation_approved_by')
    salesperson = models.ForeignKey(Employee, null=True, blank=True)
    shipping_charge = models.DecimalField(max_digits=20, decimal_places=2, default=0, null=True, blank=True)

    def __str__(self):
        return str(self.code)

    def quotecode(self):
        return self.objects.count() + 1

    def setAmount(self):
        items = self.items

        sub_total = 0
        for item in items.all():
            sub_total = sub_total + item.total_price
        self.amount = sub_total + self.shipping_charge
        return self

    def subTotal(self):
        items = self.items

        sub_total = 0
        for item in items.all():
            sub_total = sub_total + item.total_price
        return sub_total


class QuotationItem(models.Model):

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="quotation_item")
    price = models.DecimalField(max_digits=20, decimal_places=2, validators=[MinValueValidator(0)])
    quantity = models.PositiveIntegerField(default=1)
    tax = models.DecimalField(max_digits=20, decimal_places=4, null=True, blank=True, default=0)
    quotation = models.ForeignKey(Quotation, on_delete=models.CASCADE,
                                  related_name="items", null=True, blank=True)
    total_price = models.DecimalField(max_digits=20, decimal_places=4, blank=True,
                                      null=True, validators=[MinValueValidator(0)])
    total_price_excluding_tax = models.DecimalField(max_digits=20, decimal_places=4, blank=True,
                                                    null=True, validators=[MinValueValidator(0)])

    def __str__(self):
        return str(self.product) + "-" + str(self.quotation)

    def setTotalPrice(self):
        total = 0
        total = (self.price * self.quantity)
        self.total_price_excluding_tax = total
        self.tax = total * Decimal(.05)

        self.total_price = total + self.tax

quotation/forms.py
from django import forms
from django.forms import ModelForm
from .models import *


class QuotationForm(ModelForm):

    class Meta:
        model = Quotation
        widgets = {
            "customer": forms.Select(attrs={'class': "form-control", 'required': "required"}),
            "salesperson": forms.Select(attrs={'class': "form-control"}),
            "shipping_charge": forms.NumberInput(attrs={'class': "form-control"}),


        }
        fields = ['customer', 'salesperson', 'shipping_charge']


class QuotationItemForm(ModelForm):

    class Meta:
        model = QuotationItem
        widgets = {
            "product": forms.Select(attrs={'class': "form-control product", 'required': "required"}),
            "price": forms.NumberInput(attrs={'class': "form-control price", 'required': "required"}),
            "quantity": forms.NumberInput(attrs={'class': "form-control quantity", 'required': "required"}),
            "tax": forms.NumberInput(attrs={'class': "form-control tax"}),
            "total_price": forms.NumberInput(attrs={'class': "form-control total_price"}),
            "total_price_excluding_tax": forms.NumberInput(attrs={'class': "form-control total_price_excluding_tax"}),

        }
        fields = ['product', 'price', 'quantity', 'tax', 'total_price','total_price_excluding_tax']

quotation/views.py
from django.shortcuts import render
from django.views.decorators.csrf import ensure_csrf_cookie
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.utils import timezone
from django.shortcuts import get_object_or_404, render
from django.db import IntegrityError, transaction
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse_lazy, reverse
from django.forms import inlineformset_factory, modelform_factory
from quotation.forms import *
from quotation.models import Quotation


@login_required
@transaction.atomic
def create(request, enquiry_pk=None):
    quotation_form = QuotationForm(request.POST or None)
    QuotationInlineFormSet = inlineformset_factory(
        Quotation, QuotationItem, form=QuotationItemForm, extra=0, can_delete=True, min_num=1, validate_min=True)
    quotation_formset = QuotationInlineFormSet(request.POST or None)

    if request.method == "POST":
        print(quotation_formset.errors)

        if quotation_form.is_valid() and quotation_formset.is_valid():
            quotation = quotation_form.save(commit=False)
            quotation.created_by = request.user.employee
            quotation.code = "QUOTE" + str(Quotation.objects.count() + 1)
            quotation.save()

            quotation_items = quotation_formset.save(commit=False)
            print(quotation_items)
            for quotation_item in quotation_items:
                quotation_item.quotation = quotation
                quotation_item.setTotalPrice()  # set sales order foreign key
                quotation_item.save()

            quotation.setAmount().save()

            # messages.add_message(request, messages.ERROR, "Quotation created successfully")
            return HttpResponseRedirect(reverse('quotation:list'))

    context = {
        'quotationform': quotation_form,
        'quotation_formset': quotation_formset,
        'products': Product.objects.all(),
        'form_url': reverse_lazy('quotation:create'),
        'type': "Create"

    }
    return render(request, "quotation/create.html", context)


@login_required
def index(request):

    quotations = Quotation.objects.all()

    context = {
        'quotations': quotations,

    }

    return render(request, 'quotation/list.html', context)


@login_required
def detail(request, pk):

    quotation = get_object_or_404(Quotation, pk=pk)

    context = {
        'quotation': quotation,

    }

    return render(request, 'quotation/detail.html', context)

quotation/templates/quotation/create.html
{% extends "pms_temp/base.html" %} 
{% load static tz util %}
{% block content %}
{% block css %}
<link href="{% static 'css/select2.min.css' %}" rel="stylesheet"> 
<style>

.rq
{
	color:#FF0000!important;
}
</style>
{% endblock css %}

<section>
	<div class="container">
		  <div class="row">
			    <div class="col-md-12">
				      <h3>
				        Create Quotation
				      </h3>
			      <hr>
			     </div>
		   </div>
		   <div class="row">
		     <div class="col-md-12">

			    <form action="{{form_url}}" method="post" class="form-horizontal">{% csrf_token %}

	                 
                	

			        <div class="form-group">

			               <div class="col-sm-3">
			                    Customer <span class="rq">*</span>
			                  </div>
			                  <div class="col-sm-6">
			                    {{ quotationform.customer }}
			                 </div>
			        </div>
			        <div class="form-group">

			               <div class="col-sm-3">
			                    Salesperson
			                  </div>
			                  <div class="col-sm-6">
			                    {{ quotationform.salesperson }}
			                 </div>
			        </div>
			        <hr>
			       

			        <div class="form-group">
			        {{ quotation_formset.management_form }}
			        {% if quotation_formset.non_form_errors %}
			            {% for error in quotation_formset.non_form_errors %}
			                <div class="grid-form1"><span class="error_form">{{ error|escape }}</span></div>
			            {% endfor %}
			        {% endif %}
			        	

			        <div id="products">
			        <div class="col-sm-12 table-responsive">

					 <table class="table table-bordered table-responsive">
	                        <thead>
	                            <tr>
	                                <th>Product<span class="req">*</span></th>
	                                <!--<th>Actual Price</th>-->
	                                <th>Price</th> 
	                                <th>Quantity</th>
	                                <th>Taxable Value</th>
	                                <th>Tax</th>
	                                <th>Total</th>
	                                <th></th>
	                            </tr>
	                        </thead>
	                        <tbody>

	                            {% for item_form in quotation_formset %}
		                             {% for hidden in item_form.hidden_fields %}
					                    {{ hidden }}
					              	  {% endfor %}
					              	  

	                            <tr class="item">
	                                <td style="min-width: 250px;">
	                                    <div>

	                                    {{ item_form.id }}
											<select class="form-control product" id="{{ item_form.product.auto_id }}" name="{{ item_form.product.html_name }}" required="required" style="width: 100%;">
												<option value="">select</option>
												{% for product in products %}
												<option value="{{product.id}}"
													data-price="{{product.price}}"
													{% compare_uuid product.id item_form.product.value %}
												>{{product}}</option>
													
												{% endfor %}
											</select>
											{# {{ item_form.product }} #}
											{{ item_form.product.errors }}
	                                    	  
	                                        
	                                    </div>
	                                </td>
	                                <td>
	                                    <div>
	                                        {{ item_form.price }}
	                                        {{ item_form.price.errors }}
	                                    </div>
	                                </td>
	                                <td>
	                                    <div>
	                                        {{ item_form.quantity.errors }}
	                                        {{ item_form.quantity }}
	                                    </div>
	                                </td>
	                                 <td>
	                                    <div>
	                                        {{ item_form.total_price_excluding_tax.errors }}
	                                        {{ item_form.total_price_excluding_tax }}
	                                    </div>
	                                </td>
	                                <td>
	                                    <div>
	                                        {{ item_form.tax.errors }}
	                                        {{ item_form.tax }}
	                                    </div>
	                                </td>
	                               
	                                <td>
	                                    <div>
	                                        {{ item_form.total_price.errors }}
	                                        {{ item_form.total_price }}
	                                    </div>
	                                </td>
	                                
	                                <td>{% if item_form.instance.pk %}{{ item_form.DELETE }}{% endif %}</td>
	                            </tr>
	                            {% endfor %}

	                            </tbody>

	                            <tr>
	                            <td colspan="6"><strong>Subtotal</strong></td>
	                            <td id="sub-total"></td>
	                            </tr>
		                </table>
		                </div>        

			        </div>
			        </div>
			        <hr>
			        <div class="form-group">

			               
			                  <div class="col-sm-4 col-xs-6 pull-right">
			                    {{ quotationform.shipping_charge }}
			                 </div>
			                 <div class="col-sm-3 col-xs-6 pull-right">
			                   <strong> Shipping Charge</strong>
			                  </div>
			        </div>
			         <hr>
			         <div class="form-group">

			        <div class="pull-right">
			                     <strong>
			                     <span style="font-size:20px;">Amount : </span>
			                     <span id="amount" style="font-size:20px;"></span>
			                     </strong>
			                  </div>

			         	
			        </div>


			        
			        <div class="form-group">
				        <div class="col-sm-9 pull-right">
				           <button type="submit" class="btn btn-primary btn-md pull-right">Save</button>
				        </div>
			        </div>
			      </form>
			   </div>
		    </div>
		        
	</div>
</section>
{% endblock content %}

{% block footer.scripts %}


<script src="{% static 'js/jquery.formset.js' %}"></script>
<script src="{% static 'js/select2.min.js' %}"></script>

<script>
$(document).ready(function() {

	var amount = 0;
	$("#amount").text(amount)
	$('.item').formset({
	  prefix: '{{quotation_formset.prefix}}',
	  addText: '<input type="button" class="btn btn-primary btn-xs" value="ADD PRODUCT">',
	  deleteText: '<font color="red">REMOVE</font>',
	  removed: setTotalAmount,
	  added: initializeFields
	});
	// initial 
	// var total_forms_count = $('#id_placementstages_set-TOTAL_FORMS');
	// var count = parseInt(total_forms_count.val());
	// // update form count
	// total_forms_count.val(count+1);
	function initializeFields(row){
		console.log("initializeFields", row)
		var quantity = row.find(".quantity")
		attachSelect2(row.find("select.product"))

		

		// row.trigger('change')
	}
	attachSelect2($('select.product'))


	function attachSelect2(select_box){
		console.log("attachSelect2", select_box)

		select_box.select2({
		  placeholder: "Select",
		  allowClear: true
		});
	}

	var products = $("#products");
	products.on('change', function (event) {
		
		console.log(this, event)
		var ele = event.target
		var table_row = $(ele).parents('tr')
		console.log(table_row)

		// console.log('product:', table_row.find("select.product"))
		var a = 0;
		var product = table_row.find("select.product")
		console.log(product)
		var unit_price = product.find("option:selected").data("price")
		var rate_input = table_row.find(".price")
		var hsn = table_row.find(".hsn")
		
		

		
		if (product.val()){


		
		// table_row.find(".unit_price").html(unit_price)
		var rate_input = table_row.find(".price")
		if (!rate_input.val() || rate_input.val() <= 0 || $(ele).is("select.product"))
			rate_input.val(unit_price)
		
		var quantity_input = table_row.find(".quantity")
		var tax_input = table_row.find(".tax")
		// var total_price_excluding_tax_input = table_row.find(".total_price_excluding_tax")
		var total_input = table_row.find(".total_price")
		var taxable_input = table_row.find(".total_price_excluding_tax")

		total_input.prop("readonly", true)

		if(!quantity_input.val())
			quantity_input.val(1)

		var rate = rate_input.val()
			quantity = quantity_input.val()
			
			
		if (product.val()) {
			a = parseFloat(rate * quantity)
			taxable_input.val(a)
			
			
			
			tax_value = (a*.05)
			tax_input.val(tax_value)
			
			item_total = (a+tax_value).toFixed(2)
			total_input.val(item_total)		    
		    setTotalAmount()
		}

		
	}
	});


	function setTotalAmount(){
		sub_totals = $('#products').find(".total_price")
	    var amount = 0;
	    sub_totals.each(function(index, subTotal){
	    	var st = $(subTotal).val();
	    	amount += parseFloat( (isNaN(st) || st == false ) ? 0 : st );
	    });

	    $("#sub-total").text(amount)

	    add_shippping_charge(amount)
	}
		
	products.find("tr.item").each(function(index, item){
		initializeFields($(item))
	});

	var shipping_charge = $("#id_shipping_charge");
	shipping_charge.on('change', function(e){
		setTotalAmount()		
	})


	function add_shippping_charge(amount) {
		
		shipping_charge = $('#id_shipping_charge').val()
		console.log(shipping_charge)
		console.log("dp")
		if(shipping_charge)
	    	amount += parseInt(shipping_charge)

	    
	    if(shipping_charge){
	    	console.log(amount)
	    	$("#amount").text(amount)
	    }
	}




});
</script>


{% endblock footer.scripts %}

quotation/templates/quotation/detail.html
{% extends "pms_temp/base.html" %} {% load static %} {% block content %}

<section>
	<div class="container">
		  <div class="row">
			    <div class="col-md-12 col-xs-12 col-sm-12 col-lg-12">
				      <h3>
				       <strong># {{quotation.code}}</strong>

				      </h3>
				</div>
				<div class="col-md-6 col-xs-12 col-sm-6 col-lg-6">
					<h4> 
					<strong>Customer : {{quotation.customer}} </strong> 
					</h4>
				</div>
				<div class="col-md-6 col-xs-12 col-sm-6 col-lg-6">
					<div class="pull-right">
					<h4>
					<strong>Salesperson : {{quotation.salesperson}} </strong> 
					</h4>
					</div>
				
				</div>

				
			   
		  </div>
		  
		    
		   <div class="row" style="padding-top:30px;">
		     <div class="col-md-12 col-xs-12">
		            
		            <div class="table-responsive">
				     <table class="table table-bordered">
						  <thead>
						    <tr>
						      <th scope="col">#</th>
						      <th scope="col">Product</th>
						      <th scope="col">Unit Price</th>
						      <th scope="col">Quantity</th>
						      <th scope="col">Total (Excluding Tax)</th>
						      <th scope="col">Tax</th>
						      <th scope="col">Total(Including Tax)</th>
						      
						    </tr>
						  </thead>
						  <tbody>
						  {% for item in quotation.items.all %}
						    <tr>
						      <th scope="row">{{forloop.counter}}</th>
						      <td>{{item.product}}</td>
						      <td>{{item.price}}</td>
						      <td>{{item.quantity}}</td>
						      <td>{{item.total_price_excluding_tax}}</td>
						      <td>{{item.tax}}</td>
						      <td>{{item.total_price}}</td>
						      
						      
						    </tr>
						   {% endfor %}
						   <tr>
						   <td colspan="6" align="right"><strong>Total(Excluding Shipping Charge)</strong></td>
						   <td><strong>{{quotation.subTotal}}</strong></td>
						   </tr>
						   <tr>
						   <td colspan="6" align="right"><strong>Shipping Charge</strong></td>
						   <td><strong>{{quotation.shipping_charge}}</strong></td>
						   </tr>
						   <tr>
						   <td colspan="6" align="right"><strong>Amount</strong></td>
						   <td><strong>{{quotation.amount}}</strong></td>
						   </tr>
						   
						    
						  </tbody>
						</table>
						</div>
				</div>
		    </div>
		     
		     

				
			   
		  </div>
		   
		        
	</div>
</section>
{% endblock content %}

{% block footer.scripts %}

{% endblock footer.scripts %}

quotation/templates/quotation/list.html
{% extends "pms_temp/base.html" %} {% load static %} {% block content %}

<section>
	<div class="container">
		  <div class="row">
			    <div class="col-md-6 col-xs-12 col-sm-12">
				      <h2>
				       Quotations
				      </h2>
				</div>

				<div class="col-md-6 col-xs-12 col-sm-12">

				  <a href="{% url 'quotation:create' %}" class="btn btn-primary pull-right btn-xs"><i class="fa fa-plus"></i> Create Quotation </a>

				</div>
			   
		  </div>
		  
		    
		   <div class="row">
		     <div class="col-md-12 col-xs-12">
		            <hr>
		            <div class="table-responsive">
				     <table class="table">
						  <thead>
						    <tr>
						      <th scope="col">#</th>
						      <th scope="col">Code</th>
						      <th scope="col">Customer</th>
						      <th scope="col">Sales Person </th>
						      <th scope="col">Amount</th>
						      <th scope="col">View</th>
						    </tr>
						  </thead>
						  <tbody>
						  {% for quotation in quotations %}
						    <tr>
						      <th scope="row">{{forloop.counter}}</th>
						      <td>{{quotation.code}}</td>
						      <td>{{quotation.customer}}</td>
						      <td>{{quotation.salesperson}}</td>
						      <td>{{quotation.amount}}</td>
						      <td><a href="{% url 'quotation:detail' quotation.pk %}"><i class="fa fa-eye"></i></a></td>
						      
						    </tr>
						   {% endfor %}
						    
						  </tbody>
						</table>
						</div>
				</div>
		    </div>
		        
	</div>
</section>
{% endblock content %}

{% block footer.scripts %}

{% endblock footer.scripts %}