PMS/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from home import views as home
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views


urlpatterns = [


    url(r'^$', home.dashboard),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^', include('product.urls', namespace="product")),
    url(r'^', include('employee.urls', namespace="employee")),
    # url(r'^login/$', auth_views.login, name='login'),
    # url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^', include('customer.urls', namespace="customer")),
    url(r'^', include('quotation.urls', namespace="quotation")),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.conf.urls import include, url

from product import views

app_name = "product"


urlpatterns = [
    url(r'^product/', include([
        url(r'^$', views.index, name="list"),
        url(r'^create/$', views.create, name="create"),
        url(r'^(?P<pk>[^/]+)/edit/$', views.edit, name="edit"),

    ])),

]

templates/pms_temp/base.html
<!DOCTYPE html> {% load staticfiles %}
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="{% static 'css/font-awesome.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css"> {% block css %} {% endblock css %}
  <style>
  .paddo {
    padding-top: 10px;
  }
  </style>
</head>

<body>
  {% include "pms_temp/header.html" %}
  <main>
    
    {% block content %} {% endblock content %}
  </main>
  {% include "pms_temp/footer.html" %}
  <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  {% block footer.scripts %} 
  {% endblock footer.scripts %}
</body>

</html>

templates/pms_temp/dashboard.html
{% extends "pms_temp/base.html" %}  
{% load staticfiles %}
{% block css %}

<link rel="stylesheet" type="text/css" href="{% static "vendor/bootstrap/css/bootstrap.min.css" %}" media="screen">
<link rel="stylesheet" type="text/css" href="{% static "vendor/metisMenu/metisMenu.min.css" %}" media="screen">
<link rel="stylesheet" type="text/css" href="{% static "dist/css/sb-admin-2.css" %}" media="screen">
<link rel="stylesheet" type="text/css" href="{% static "vendor/morrisjs/morris.css" %}" media="screen">
<link rel="stylesheet" type="text/css" href="{% static "vendor/font-awesome/css/font-awesome.min.css" %}" media="screen">
{% endblock css %}
{% block content %}

<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            

            

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">

                        <li>

                            <a href="{% url 'employee:list' %}"><i class="fa fa-user fa-fw"></i>Employee<span class="fa arrow"></span></a>
                            
                        </li>
                        <li>

                            <a href="{% url 'customer:list' %}"><i class="fa fa-user fa-fw"></i>Customers<span class="fa arrow"></span></a>
                            
                        </li>
                        
                       
                        
                       
                        <li>

                            <a href="{% url 'product:list' %}"><i class="fa fa-product-hunt fa-fw"></i>Products<span class="fa arrow"></span></a>
                            
                        </li>
                         <li>

                            <a href="{% url 'quotation:list' %}"><i class="fa fa-question fa-fw"></i>Quotation<span class="fa arrow"></span></a>
                            
                        </li>
                        
                        
                        

                        
                           
                        
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                   
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row" style="margin-top:20px;">
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-users fa-4x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge"></div>
                                    <div>Employees</div>
                                </div>
                            </div>
                        </div>
                        <a href="{% url 'employee:list' %}">
                            <div class="panel-footer">
                                <span class="pull-left">View Details</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-green">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-users fa-4x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge"></div>
                                    <div>Customers</div>
                                </div>
                            </div>
                        </div>
                        <a href="{% url 'customer:list' %}">
                            <div class="panel-footer">
                                <span class="pull-left">View Details</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-yellow">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-product-hunt fa-4x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge"></div>
                                    <div> Products</div>
                                </div>
                            </div>
                        </div>
                        <a href="{% url 'product:list' %}">
                            <div class="panel-footer">
                                <span class="pull-left">View Details</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-red">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-question fa-4x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge"></div>
                                    <div> Quotations</div>
                                </div>
                            </div>
                        </div>
                        <a href="{% url 'quotation:list' %}">
                            <div class="panel-footer">
                                <span class="pull-left">View Details</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>
               
            </div>


             </div>


    </div>

</body>
{% endblock content %}
{% block footer.scripts %}

<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'vendor/metisMenu/metisMenu.min.js' %}"></script>
<script src="{% static 'vendor/raphael/raphael.min.js' %}"></script>
<script src="{% static 'dist/js/sb-admin-2.js' %}"></script>
{% endblock footer.scripts %}

templates/pms_temp/header.html
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-ex-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><strong>PMS</strong></a>
    </div>
    <div class="collapse navbar-collapse" id="navbar-ex-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li class="active">
          <a href="/">Home</a>
        </li>
        
        <li>
          {% if user.is_authenticated %}
            <a href="{% url 'account_logout' %}">Logout</a>
          {% else %}
            <a href="{% url 'account_login' %}">Login</a>
          {% endif %}
        </li>
      </ul>
    </div>
  </div>
</nav>

templates/pms_temp/index.html
<!--{% extends "pms/base.html" %} {% block content %}
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-4 col-md-offset-4">
      <div class="panel panel-primary login">
        <div class="panel-heading">
          <h4 class="text-center">Login</h4>
        </div>
        <div class="panel-body">
          <form action="" method="post" class="login-form">
            {% csrf_token %}
            <div class="">
              <div class="form-group">
                <input type="text" class="form-control login-field" value="" placeholder="Enter your name" id="login-name" name="login-name" />
                <label class="login-field-icon fui-user" for="login-name"></label>
              </div>
              <div class="form-group">
                <input type="password" class="form-control login-field" value="" placeholder="Password" id="login-pass" name="login-pass" />
                <label class="login-field-icon fui-lock" for="login-pass"></label>
              </div>
              {% if redirect_field_value %}
              <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
              {% endif %}
              <button type="submit" class="btn btn-primary btn-lg btn-block">Log In</button>
              <a class="login-link" href="#">Lost your password?</a>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
{% endblock content %}-->
<html>
<body>
hi
</body>
</html>